// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Records the effective multi-agent delegation instructions for a turn.
 * `none` is retained for deprecated API fields and legacy rollout compatibility;
 * current runtime behavior does not select it.
 */
export type MultiAgentMode = "none" | "explicitRequestOnly" | "proactive";
